version: '3.9'
services:
  app:
    container_name: golang_container
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgresdb:5432/postgres
    tty: true
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgresdb
    networks:
      - learning

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - app
  
  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: pg_isready -U postgres
    ports:
      - '5432:5432'
    networks:
      - learning

# Networks to be created to facilitate communication between containers
networks:
  learning:
    driver: bridge